server:
  port: 8083
spring:
  application:
    name: sms-service
  datasource:
    url: jdbc:mysql://localhost:3306/moyu_store?useUnicoding=true&characterEncoding=utf-8
    username: debian-sys-maint
    password: GsIUsuchqkWQAe0D
    driver-class-name: com.mysql.jdbc.Driver

moyu:
  sms:
    accessKeyId: LTAINyOLf8uDYpnD # 自己的accesskeyId
    accessKeySecret: dpqjYOcsm0jdBjdt7c6shWgtvQIuUJ
    signName: MoyuStore # 签名名称
    verifyCodeTemplate: SMS_163725749 # 模板名称

eureka:
  client:
    service-url:
     defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

mybatis:
  type-aliases-package: com.moyu.user.pojo